# ml-predictive-scaler-hpa.yaml
# This file defines a Horizontal Pod Autoscaler (HPA) for the
# ml-predictive-scaler deployment. The predictive controller will
# ideally update this HPA's min/max replicas or target metrics
# based on its predictions.

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ml-predictive-scaler-hpa
  namespace: default # Must be in the same namespace as the deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ml-predictive-scaler # Name of the deployment to scale
  minReplicas: 1 # Minimum number of replicas
  maxReplicas: 2 # Maximum number of replicas (adjust as needed)
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Default target CPU utilization. The controller will "override" this conceptually.
